### ISSUE TITLE
在 CentOS 5.8 启动报错

### ISSUE THREAD

**Issue by Cat7373** [fatedier/frp#1438]
**What version of frp are you using (./frpc -v or ./frps -v)?**
0.29.0

**What operating system and processor architecture are you using (`go env`)?**
```
[root@localhost frp]# uname -a
Linux localhost.localdomain 2.6.18-308.24.1.el5 #1 SMP Tue Dec 4 17:43:34 EST 2012 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost frp]# lsb_release -a
LSB Version:	:core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 5.8 (Final)
Release:	5.8
Codename:	Final
```

**Configures you used:**
```
[common]
bind_port = 25564
```

**Steps to reproduce the issue:**
1. ./frps -c ./frps.ini

**Describe the results you received:**
```
[root@localhost frp]# ./frps -c ./frps.ini
runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x956166, 0x17)
	/home/wcl/.gvm/gos/go1.12.9/src/runtime/panic.go:617 +0x72
runtime.netpoll(0x131e6667771b00, 0x0)
	/home/wcl/.gvm/gos/go1.12.9/src/runtime/netpoll_epoll.go:75 +0x209
runtime.sysmon()
	/home/wcl/.gvm/gos/go1.12.9/src/runtime/proc.go:4326 +0x374
runtime.mstart1()
	/home/wcl/.gvm/gos/go1.12.9/src/runtime/proc.go:1206 +0xc4
runtime.mstart()
	/home/wcl/.gvm/gos/go1.12.9/src/runtime/proc.go:1172 +0x6f

goroutine 1 [runnable]:
github.com/fatedier/frp/server/ports.NewPortManager(0x94e518, 0x3, 0x94f03c, 0x7, 0xc00001f740, 0x0)
	/home/wcl/go_projects/src/github.com/fatedier/frp/server/ports/ports.go:56 +0x12b
github.com/fatedier/frp/server.NewService(0x94f03c, 0x7, 0x63dc, 0x0, 0x0, 0x94f03c, 0x7, 0x0, 0x0, 0x3c, ...)
	/home/wcl/go_projects/src/github.com/fatedier/frp/server/service.go:97 +0x164
main.runServer(0x94f03c, 0x7, 0x63dc, 0x0, 0x0, 0x94f03c, 0x7, 0x0, 0x0, 0x3c, ...)
	/home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frps/root.go:201 +0xce
main.glob..func1(0xee96e0, 0xc00000c860, 0x0, 0x2, 0x0, 0x0)
	/home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frps/root.go:116 +0x13d
github.com/fatedier/frp/vendor/github.com/spf13/cobra.(*Command).execute(0xee96e0, 0xc00001e1c0, 0x2, 0x2, 0xee96e0, 0xc00001e1c0)
	/home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/fatedier/frp/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xee96e0, 0xc00000c040, 0x15c3f4f81144d900, 0xc00001e058)
	/home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/fatedier/frp/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/spf13/cobra/command.go:800
main.Execute()
	/home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frps/root.go:126 +0x2e
main.main()
	/home/wcl/go_projects/src/github.com/fatedier/frp/cmd/frps/main.go:30 +0xb2

goroutine 5 [runnable]:
github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go.(*updateHeap).updateTask(0xeef1c0)
	/home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go/updater.go:78
created by github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go.init.2
	/home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go/updater.go:13 +0x70

goroutine 6 [runnable]:
text/template/parse.(*lexer).emit(...)
	/home/wcl/.gvm/gos/go1.12.9/src/text/template/parse/lex.go:156
text/template/parse.lexText(0xc0000ce200, 0x0)
	/home/wcl/.gvm/gos/go1.12.9/src/text/template/parse/lex.go:267 +0x514
text/template/parse.(*lexer).run(0xc0000ce200)
	/home/wcl/.gvm/gos/go1.12.9/src/text/template/parse/lex.go:228 +0x37
created by text/template/parse.lex
	/home/wcl/.gvm/gos/go1.12.9/src/text/template/parse/lex.go:221 +0x134
```

**Describe the results you expected:**
normal work.

**Additional information you deem important (e.g. issue happens only occasionally):**
none

**Can you point out what caused this issue (optional)**
none

**Comment by fatedier** [comment]
https://github.com/golang/go/wiki/MinimumRequirements#linux

> Kernel version 2.6.23 or later. [This depends on architecture though, we need to have specific builder for this.] Linux/ARMv5 requires much newer kernels, at least v3.1 (for __kuser_cmpxchg64).

> We don't support CentOS 5. The kernel is too old (2.6.18).
