### ISSUE TITLE
关于RDP连接的一个问题

### ISSUE THREAD

**Issue by i0bris** [fatedier/frp#1492]
关于一个使用KCP底层进行RDP远程桌面连接FRPS的一个报错问题。

使用环境是 谷歌云服务器
FRP版本号是 0.29.0
```
panic: unreachable

goroutine 5 [running]:
github.com/fatedier/frp/vendor/github.com/klauspost/reedsolomon.reedSolomon.codeSomeShardsAvx512(...)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/klauspost/reedsolomon/galois_noasm.go:33
github.com/fatedier/frp/vendor/github.com/klauspost/reedsolomon.reedSolomon.codeSomeShards(0xa, 0x3, 0xd, 0x9c92460, 0xd, 0xd, 0x9c1ee00, 0x9c61000, 0xa, 0xa, ...)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/klauspost/reedsolomon/reedsolomon.go:441 +0x374
github.com/fatedier/frp/vendor/github.com/klauspost/reedsolomon.reedSolomon.Encode(0xa, 0x3, 0xd, 0x9c92460, 0xd, 0xd, 0x9c1ee00, 0x9c61000, 0xa, 0xa, ...)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/klauspost/reedsolomon/reedsolomon.go:313 +0x142
github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go.(*fecEncoder).encode(0x9c59270, 0xa070580, 0x20, 0x546, 0x3, 0x8093060, 0x77ea6097)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go/fec.go:281 +0x2b2
github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go.(*UDPSession).output(0x9c0a3c0, 0xa070580, 0x20, 0x546)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go/sess.go:515 +0x5c4
github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go.newUDPSession.func1(0xa070580, 0x546, 0x546, 0x20)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go/sess.go:169 +0x4a
github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go.(*KCP).flush.func2(...)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go/kcp.go:685
github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go.(*KCP).flush(0x9c949c0, 0x0, 0x89d72e0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go/kcp.go:842 +0xbe8
github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go.(*UDPSession).update(0x9c0a3c0, 0xbf671e35, 0x77ff1dc8)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go/sess.go:556 +0x53
github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go.(*updateHeap).updateTask(0x89d6f80)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go/updater.go:91 +0xfd
created by github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go.init.2
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/fatedier/kcp-go/updater.go:13 +0x60
```

当某个RDP连接到FRPS时报错如上信息。

**Comment by fatedier** [comment]
错误信息还有吗，方便全贴上来吗？

**Comment by i0bris** [comment]
> 错误信息还有吗，方便全贴上来吗？

目前就收集到的是这些错误信息，当客户端关闭kcp底层通信的时候一切正常，frps不会报错。
