### ISSUE TITLE
自己编译的 OpenWrt 的包，会出现一定概率的崩溃，其它平台正常

### ISSUE THREAD

**Issue by botsphp** [fatedier/frp#1703]
不重要不紧急，有时间看看就好，估计用的人不多。

```
SIGILL: illegal instruction
PC=0x89174 m=3 sigcode=128

goroutine 1 [running]:
runtime.asyncPreempt()
    /usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_mipsx.s:40 +0x7c fp=0x11b37e4 sp=0x11b36f0 pc=0x89174
hash/crc32.slicingUpdate(0xb50467eb, 0x11ca000, 0x128fe00, 0x10000, 0x10000, 0x146100)
    /usr/local/Cellar/go/1.14/libexec/src/hash/crc32/crc32_generic.go:77 +0x64 fp=0x11b3804 sp=0x11b37e8 pc=0x10354c
hash/crc32.ieeeInit.func1(0xb50467eb, 0x128fe00, 0x10000, 0x10000, 0x0)
    /usr/local/Cellar/go/1.14/libexec/src/hash/crc32/crc32.go:117 +0x60 fp=0x11b3820 sp=0x11b3804 pc=0x103794
hash/crc32.(*digest).Write(0x1096da8, 0x128fe00, 0x10000, 0x10000, 0x10000, 0x0, 0x0)
    /usr/local/Cellar/go/1.14/libexec/src/hash/crc32/crc32.go:231 +0x90 fp=0x11b383c sp=0x11b3820 pc=0x102e40
archive/zip.(*checksumReader).Read(0x10c23f0, 0x128fe00, 0x10000, 0x10000, 0x8000, 0x0, 0x0)
    /usr/local/Cellar/go/1.14/libexec/src/archive/zip/reader.go:195 +0xc4 fp=0x11b3870 sp=0x11b383c pc=0x146154
bytes.(*Buffer).ReadFrom(0x11b38d0, 0x6f46c108, 0x10c23f0, 0x515e00, 0x51f3c0, 0x6f46c108, 0x58dd)
    /usr/local/Cellar/go/1.14/libexec/src/bytes/buffer.go:204 +0xd8 fp=0x11b38ac sp=0x11b3870 pc=0xc6608
io/ioutil.readAll(0x6f46c108, 0x10c23f0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.14/libexec/src/io/ioutil/ioutil.go:36 +0xfc fp=0x11b38ec sp=0x11b38ac pc=0x142f20
io/ioutil.ReadAll(...)
    /usr/local/Cellar/go/1.14/libexec/src/io/ioutil/ioutil.go:45
github.com/rakyll/statik/fs.unzip(0x10b8e80, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/rakyll/statik@v0.1.1/fs/fs.go:77 +0xf0 fp=0x11b3920 sp=0x11b38ec pc=0x34a574
github.com/rakyll/statik/fs.New(0x4, 0x6470e4, 0x10e2500, 0x10)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/rakyll/statik@v0.1.1/fs/fs.go:59 +0x138 fp=0x11b3990 sp=0x11b3920 pc=0x34a18c
github.com/fatedier/frp/assets.Load(...)
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/assets/assets.go:47
github.com/fatedier/frp/client.(*Service).Run(0x10e2500, 0x5, 0x0)
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/service.go:125 +0x5a8 fp=0x11b3bac sp=0x11b3990 pc=0x493f14
github.com/fatedier/frp/cmd/frpc/sub.startService(0x579bd0, 0x5, 0x0, 0x579074, 0x0, 0x579074, 0x0, 0x579074, 0x0, 0x579074, ...)
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/cmd/frpc/sub/root.go:228 +0x144 fp=0x11b3cb8 sp=0x11b3bac pc=0x49dd98
github.com/fatedier/frp/cmd/frpc/sub.runClient(0x7febfed8, 0x11, 0x10b8a00, 0x5796ba)
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/cmd/frpc/sub/root.go:196 +0x16c fp=0x11b3e7c sp=0x11b3cb8 pc=0x49dc04
github.com/fatedier/frp/cmd/frpc/sub.glob..func4(0x9dd8c0, 0x109e410, 0x0, 0x2, 0x0, 0x0)
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/cmd/frpc/sub/root.go:94 +0x5c fp=0x11b3eb0 sp=0x11b3e7c pc=0x4a355c
github.com/spf13/cobra.(*Command).execute(0x9dd8c0, 0x10a0128, 0x2, 0x3, 0x9dd8c0, 0x10a0128)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x3c8 fp=0x11b3f18 sp=0x11b3eb0 pc=0x399fe0
github.com/spf13/cobra.(*Command).ExecuteC(0x9dd8c0, 0xc9f0f79f, 0x15fc248e, 0x10a0018)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x284 fp=0x11b3f7c sp=0x11b3f18 pc=0x39a8c4
github.com/spf13/cobra.(*Command).Execute(...)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/fatedier/frp/cmd/frpc/sub.Execute()
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/cmd/frpc/sub/root.go:104 +0x40 fp=0x11b3f90 sp=0x11b3f7c pc=0x49d35c
main.main()
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/cmd/frpc/main.go:31 +0x160 fp=0x11b3fc0 sp=0x11b3f90 pc=0x4a5c40
runtime.main()
    /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:203 +0x284 fp=0x11b3fec sp=0x11b3fc0 pc=0x50a18
runtime.goexit()
    /usr/local/Cellar/go/1.14/libexec/src/runtime/asm_mipsx.s:651 +0x4 fp=0x11b3fec sp=0x11b3fec pc=0x889f4

goroutine 18 [select]:
github.com/fatedier/kcp-go.(*updateHeap).updateTask(0x9e34e0)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/updater.go:81 +0x35c
created by github.com/fatedier/kcp-go.init.2
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/fatedier/kcp-go@v2.0.4-0.20190803094908-fe8645b0a904+incompatible/updater.go:13 +0x8c

goroutine 20 [chan receive]:
github.com/fatedier/beego/logs.(*fileLogWriter).dailyRotate(0x10b8b80, 0x2526f202, 0xbf9349fd, 0xde9f0c, 0x0, 0x9e37a0)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/fatedier/beego@v0.0.0-20171024143340-6c6a4f5bd5eb/logs/file.go:197 +0x314
created by github.com/fatedier/beego/logs.(*fileLogWriter).initFd
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/fatedier/beego@v0.0.0-20171024143340-6c6a4f5bd5eb/logs/file.go:180 +0x2d0

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x6f46bf60, 0x72, 0xffffffff)
    /usr/local/Cellar/go/1.14/libexec/src/runtime/netpoll.go:203 +0x60
internal/poll.(*pollDesc).wait(0x10fe974, 0x72, 0x1000, 0x1000, 0xffffffff)
    /usr/local/Cellar/go/1.14/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x50
internal/poll.(*pollDesc).waitRead(...)
    /usr/local/Cellar/go/1.14/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x10fe960, 0x11b4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.14/libexec/src/internal/poll/fd_unix.go:169 +0x1ac
net.(*netFD).Read(0x10fe960, 0x11b4000, 0x1000, 0x1000, 0x17, 0x0, 0x0)
    /usr/local/Cellar/go/1.14/libexec/src/net/fd_unix.go:202 +0x58
net.(*conn).Read(0x1096c60, 0x11b4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.14/libexec/src/net/net.go:184 +0x94
bufio.(*Reader).Read(0x10c2270, 0x1106000, 0xc, 0xc, 0xc, 0x0, 0x0)
    /usr/local/Cellar/go/1.14/libexec/src/bufio/bufio.go:226 +0x294
io.ReadAtLeast(0x6df160, 0x10c2270, 0x1106000, 0xc, 0xc, 0xc, 0xc, 0x0, 0x0)
    /usr/local/Cellar/go/1.14/libexec/src/io/io.go:310 +0x98
io.ReadFull(...)
    /usr/local/Cellar/go/1.14/libexec/src/io/io.go:329
github.com/hashicorp/yamux.(*Session).recvLoop(0x10a3570, 0x0, 0x0)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/hashicorp/yamux@v0.0.0-20181012175058-2f1d1f20f75d/session.go:458 +0xc8
github.com/hashicorp/yamux.(*Session).recv(0x10a3570)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/hashicorp/yamux@v0.0.0-20181012175058-2f1d1f20f75d/session.go:437 +0x3c
created by github.com/hashicorp/yamux.newSession
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/hashicorp/yamux@v0.0.0-20181012175058-2f1d1f20f75d/session.go:113 +0x268

goroutine 22 [select]:
github.com/hashicorp/yamux.(*Session).send(0x10a3570)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/hashicorp/yamux@v0.0.0-20181012175058-2f1d1f20f75d/session.go:399 +0x23c
created by github.com/hashicorp/yamux.newSession
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/hashicorp/yamux@v0.0.0-20181012175058-2f1d1f20f75d/session.go:114 +0x28c

goroutine 23 [select]:
github.com/hashicorp/yamux.(*Session).keepalive(0x10a3570)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/hashicorp/yamux@v0.0.0-20181012175058-2f1d1f20f75d/session.go:313 +0xcc
created by github.com/hashicorp/yamux.newSession
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/hashicorp/yamux@v0.0.0-20181012175058-2f1d1f20f75d/session.go:116 +0x2d8

goroutine 24 [chan receive]:
github.com/fatedier/frp/client.(*Control).worker(0x10da6e0)
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/control.go:343 +0xb8
created by github.com/fatedier/frp/client.(*Control).Run
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/control.go:125 +0x50

goroutine 25 [select]:
github.com/fatedier/frp/client/proxy.(*ProxyWrapper).checkWorker(0x10de320)
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/proxy/proxy_wrapper.go:192 +0x1dc
created by github.com/fatedier/frp/client/proxy.(*ProxyWrapper).Start
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/proxy/proxy_wrapper.go:128 +0x50

goroutine 33 [select]:
github.com/fatedier/frp/client.(*Control).msgHandler(0x10da6e0)
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/control.go:296 +0x25c
created by github.com/fatedier/frp/client.(*Control).worker
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/control.go:338 +0x50

goroutine 26 [sleep]:
time.Sleep(0x540be400, 0x2)
    /usr/local/Cellar/go/1.14/libexec/src/runtime/time.go:198 +0x110
github.com/fatedier/frp/client.(*VisitorManager).Run(0x10c22d0)
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/visitor_manager.go:51 +0x21c
created by github.com/fatedier/frp/client.(*Control).Run
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/control.go:131 +0x94

goroutine 34 [select]:
github.com/hashicorp/yamux.(*Stream).Read(0x10a35e0, 0x1106070, 0x1, 0x1, 0x0, 0x0, 0x0)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/hashicorp/yamux@v0.0.0-20181012175058-2f1d1f20f75d/stream.go:133 +0x3f0
crypto/cipher.StreamReader.Read(0x6df260, 0x1118060, 0x6f46c078, 0x10a35e0, 0x1106070, 0x1, 0x1, 0x50f9c, 0x3dfe30, 0x10)
    /usr/local/Cellar/go/1.14/libexec/src/crypto/cipher/io.go:20 +0x5c
github.com/fatedier/golib/crypto.(*Reader).Read(0x1118030, 0x1106070, 0x1, 0x1, 0x14b5c, 0x10b4fc0, 0x1052200)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/fatedier/golib@v0.0.0-20181107124048-ff8cd814b049/crypto/decode.go:70 +0x90
github.com/fatedier/golib/msg/json.(*MsgCtl).readMsg(0x109e180, 0x6df520, 0x1118030, 0x825e4, 0x10b4fc0, 0x4921d8, 0x10b4fc0, 0x112efc4, 0x9f2701)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/fatedier/golib@v0.0.0-20181107124048-ff8cd814b049/msg/json/process.go:32 +0x7c
github.com/fatedier/golib/msg/json.(*MsgCtl).ReadMsg(0x109e180, 0x6df520, 0x1118030, 0x4d8b40, 0x9f272c, 0x0, 0x0)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/fatedier/golib@v0.0.0-20181107124048-ff8cd814b049/msg/json/process.go:68 +0x4c
github.com/fatedier/frp/models/msg.ReadMsg(...)
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/models/msg/ctl.go:37
github.com/fatedier/frp/client.(*Control).reader(0x10da6e0)
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/control.go:239 +0x24c
created by github.com/fatedier/frp/client.(*Control).worker
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/control.go:339 +0x74

goroutine 27 [chan receive]:
github.com/fatedier/frp/client.(*Service).keepControllerWorking(0x10e2500)
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/service.go:146 +0x368
created by github.com/fatedier/frp/client.(*Service).Run
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/service.go:121 +0x2cc

goroutine 35 [runnable]:
time.resetTimer(0x119c204, 0xf964fe58, 0x1795)
    /usr/local/Cellar/go/1.14/libexec/src/runtime/time.go:233 +0x4c
time.(*Timer).Reset(0x119c200, 0x540be400, 0x2, 0x0)
    /usr/local/Cellar/go/1.14/libexec/src/time/sleep.go:126 +0xa4
github.com/hashicorp/yamux.(*Session).waitForSendErr(0x10a3570, 0x10b2d00, 0xc, 0xc, 0x6df1e0, 0x119e120, 0x10b4dc0, 0x0, 0x0)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/hashicorp/yamux@v0.0.0-20181012175058-2f1d1f20f75d/session.go:341 +0xb0
github.com/hashicorp/yamux.(*Stream).write(0x10a35e0, 0x120a010, 0x10, 0x10, 0x9, 0x1ac, 0x1ac)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/hashicorp/yamux@v0.0.0-20181012175058-2f1d1f20f75d/stream.go:194 +0x508
github.com/hashicorp/yamux.(*Stream).Write(0x10a35e0, 0x120a010, 0x10, 0x10, 0x0, 0x0, 0x0)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/hashicorp/yamux@v0.0.0-20181012175058-2f1d1f20f75d/stream.go:150 +0x128
github.com/fatedier/golib/crypto.(*Writer).Write(0x120c060, 0x1230000, 0x135, 0x1ac, 0x135, 0x1ac, 0x0)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/fatedier/golib@v0.0.0-20181107124048-ff8cd814b049/crypto/encode.go:77 +0x158
github.com/fatedier/golib/msg/json.(*MsgCtl).WriteMsg(0x109e180, 0x6df540, 0x120c060, 0x4d8980, 0x1116000, 0x120c060, 0x0)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/fatedier/golib@v0.0.0-20181107124048-ff8cd814b049/msg/json/process.go:89 +0x8c
github.com/fatedier/frp/models/msg.WriteMsg(...)
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/models/msg/ctl.go:45
github.com/fatedier/frp/client.(*Control).writer(0x10da6e0)
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/control.go:269 +0x268
created by github.com/fatedier/frp/client.(*Control).worker
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/control.go:340 +0x98

goroutine 49 [runnable]:
sync.(*Pool).pin(0x9e30c0, 0x1122180, 0x1122180)
    /usr/local/Cellar/go/1.14/libexec/src/sync/pool.go:195 +0x1c
sync.(*Pool).Put(0x9e30c0, 0x56d940, 0x1128060)
    /usr/local/Cellar/go/1.14/libexec/src/sync/pool.go:102 +0x48
encoding/json.Marshal(0x4d8a80, 0x1102140, 0x1206f4c, 0x10da621, 0x536b01, 0x1104018, 0x492200)
    /usr/local/Cellar/go/1.14/libexec/src/encoding/json/encode.go:167 +0x100
github.com/fatedier/golib/msg/json.(*MsgCtl).Pack(0x109e180, 0x4d8a80, 0x1102140, 0x49150c, 0x515fe0, 0x567c80, 0x0, 0x6f46c048)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/fatedier/golib@v0.0.0-20181107124048-ff8cd814b049/msg/json/pack.go:56 +0xc8
github.com/fatedier/golib/msg/json.(*MsgCtl).WriteMsg(0x109e180, 0x6f46c048, 0x1132070, 0x4d8a80, 0x1102140, 0x6f46c078, 0x10)
    /Users/botsphp/wwwroot/gopath/pkg/mod/github.com/fatedier/golib@v0.0.0-20181107124048-ff8cd814b049/msg/json/process.go:84 +0x4c
github.com/fatedier/frp/models/msg.WriteMsg(...)
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/models/msg/ctl.go:45
github.com/fatedier/frp/client.(*Control).HandleReqWorkConn(0x10da6e0, 0x9f272c)
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/control.go:149 +0x1e8
created by github.com/fatedier/frp/client.(*Control).msgHandler
    /Users/botsphp/wwwroot/gopath/src/github.com/fatedier/frp/client/control.go:320 +0x2f8

r0   0x0    r1   0xb4ca8b09
r2   0x42098a25 r3   0x11ca000
r4   0x1295ac0  r5   0xa340
r6   0x8    r7   0x6f
r8   0x70   r9   0x11cbc00
r10  0x170  r11  0x62222c22
r12  0x64657461 r13  0x64707522
r14  0x2c226574 r15  0x61647055
r16  0x3    r17  0xf
r18  0x1    r19  0x1
r20  0x11b38d0  r21  0x1280000
r22  0x6472c0   r23  0x0
r24  0x0    r25  0x0
r26  0x802  r27  0x0
r28  0x0    r29  0x11b36f0
r30  0x10000e0  r31  0x10354c
pc   0x89174    link 0x10354c
lo   0x0    hi   0x0
```

**Comment by fatedier** [comment]
这个是 go1.14 新增的抢占式调度的功能引起的。至于为什么在 OpenWRT 上会有这个问题以及如何修复目前不是很清楚，能力有限，可以尝试给 golang 的官方 repo 提个 issue 可能更好一些。

**Comment by botsphp** [comment]
我回头试一下把 go 降到 14以下编译一下看看有没有问题。

**Comment by botsphp** [comment]
目前可以确认1.13没有问题。
