### ISSUE TITLE
连续启动两次frpc客户端，frps即奔溃

### ISSUE THREAD

**Issue by LitleCarl** [fatedier/frp#223]
关键信息：panic: close of nil channel
原因：由于客户端网络不稳定或者其他原因，我希望每次连上fprs后，能把同名的frpc踢掉，我看了[代码](https://github.com/fatedier/frp/blob/edb97abf50c78dd514116e236a68eb954b6d6aa6/src/models/server/config.go#L400)中也确实是这样的逻辑，但是每次重复frpc连接，frps就crash了，log如下

> 2017/01/12 10:56:38 [control.go:273] [W] ProxyName [web02], this proxy is already working now
> panic: close of nil channel
> 
> goroutine 18 [running]:
> panic(0x764840, 0xc420163630)
> 	/home/wcl/.gvm/gos/go1.7.4/src/runtime/panic.go:500 +0x1a1
> github.com/fatedier/frp/src/models/server.(*ProxyServer).Release(0xc42006b1e0)
> 	/home/wcl/go_projects/src/github.com/fatedier/frp/src/models/server/server.go:301 +0x9c
> github.com/fatedier/frp/src/models/server.(*ProxyServer).Close(0xc42006b1e0)
> 	/home/wcl/go_projects/src/github.com/fatedier/frp/src/models/server/server.go:283 +0x6f
> main.controlWorker.func1(0xc42019be97, 0xc42001d9c0, 0xc42019bed0)
> 	/home/wcl/go_projects/src/github.com/fatedier/frp/src/cmd/frps/control.go:53 +0x5e
> main.controlWorker(0xc42001d9c0)
> 	/home/wcl/go_projects/src/github.com/fatedier/frp/src/cmd/frps/control.go:94 +0x5ea
> created by main.ProcessControlConn
> 	/home/wcl/go_projects/src/github.com/fatedier/frp/src/cmd/frps/control.go:40 +0x10c

**Comment by LitleCarl** [comment]
刚看到0.9.2更新了，不好意思没看到。谢谢
