### ISSUE TITLE
XTCP 出现了invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by iikira** [fatedier/frp#2272]
错误日志：
```log
2021/03/02 04:16:59 [E] [proxy.go:793] [6f4ed237f1d7dc2d] [esxi_openwrt_msi_windows_openssh] connect to local service [192.168.2.7:22] error: dial tcp 192.168.2.7:22: connect: no route to host
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x85e37f]

goroutine 291652 [running]:
github.com/fatedier/frp/client/proxy.(*XTCPProxy).InWorkConn(0xc00008e400, 0xac3120, 0xc0001d20c0, 0xc0000a90e0)
        github.com/fatedier/frp/client/proxy/proxy.go:312 +0x37f
created by github.com/fatedier/frp/client/proxy.(*Wrapper).InWorkConn
        github.com/fatedier/frp/client/proxy/proxy_wrapper.go:232 +0x248
```

查询源码发现错误所在
https://github.com/fatedier/frp/blob/78b8bb7bc6936acae2da6de4eddb877a3fd1d910/client/proxy/proxy.go#L312

```go
	clientConn, err := net.DialUDP("udp", nil, raddr)
	defer clientConn.Close()

	err = msg.WriteMsg(clientConn, natHoleClientMsg)
	if err != nil {
		xl.Error("send natHoleClientMsg to server error: %v", err)
		return
	}
```

可能的解决办法，将defer语句移到错误处理代码之后

**Comment by fatedier** [comment]
@iikira 那边应该漏了一个错误处理，如果 DialUDP error，就但因错误并且 return，你能提一个 PR 修复吗？
