### ISSUE TITLE
panic error: send on closed channel

### ISSUE THREAD

**Issue by gam2046** [fatedier/frp#2361]
**[REQUIRED] hat version of frp are you using** 

Version: 0.35.1

**[REQUIRED] What operating system and processor architecture are you using**
OS: Debian 4.19.181-1 (2021-03-19) 
CPU architecture: x86_64

**[REQUIRED] description of errors**

**confile**

**log file**

```
2021/04/21 12:48:42 [E] [control.go:324] [0e9f2f4b2c7d39e2] panic error: send on closed channel
2021/04/21 12:48:42 [E] [control.go:325] [0e9f2f4b2c7d39e2] goroutine 1294227 [running]:
runtime/debug.Stack(0xc0000b8070, 0x3, 0xc0090bc8c0)
        runtime/debug/stack.go:24 +0x9f
github.com/fatedier/frp/server.(*Control).reader.func1(0xc008bdfe30)
        github.com/fatedier/frp/server/control.go:325 +0xe5
panic(0xa36ac0, 0xd04260)
        runtime/panic.go:969 +0x1b9
github.com/fatedier/frp/server.(*Control).reader(0xc001df4c00)
        github.com/fatedier/frp/server/control.go:345 +0x279
created by github.com/fatedier/frp/server.(*Control).Start
        github.com/fatedier/frp/server/control.go:204 +0x1be

2021/04/21 13:00:28 [E] [control.go:324] [cca6c8262e2a4777] panic error: send on closed channel
2021/04/21 13:00:28 [E] [control.go:325] [cca6c8262e2a4777] goroutine 1458212 [running]:
runtime/debug.Stack(0xc0000b8070, 0x3, 0xc0090731c0)
        runtime/debug/stack.go:24 +0x9f
github.com/fatedier/frp/server.(*Control).reader.func1(0xc0094fa330)
        github.com/fatedier/frp/server/control.go:325 +0xe5
panic(0xa36ac0, 0xd04260)
        runtime/panic.go:969 +0x1b9
github.com/fatedier/frp/server.(*Control).reader(0xc0049a9b00)
        github.com/fatedier/frp/server/control.go:345 +0x279
created by github.com/fatedier/frp/server.(*Control).Start
        github.com/fatedier/frp/server/control.go:204 +0x1be
```
**Steps to reproduce the issue**
1. When there are about 2,000 devices connected, maintaining it for a period of time will lead to application Crash
2. 
3. 

**Supplementary information**

**Can you guess what caused this issue**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by fatedier** [comment]
Can you paste more log before these error messages?
