### ISSUE TITLE
Dashboard freezes when accessing proxy details

### ISSUE THREAD

**Issue by manprint** [fatedier/frp#3397]
### Bug Description

Hi @fatedier, when accessing the dashboard to view proxy details (when expanding entries) http, https, tcp the dashboard page freezes and you need to close the tab and reopen it.

Then, once the entries of the various proxies have been opened, they no longer close and there are errors in the browser console
I am attaching the error

![error](https://user-images.githubusercontent.com/64725303/231017259-f8da9ba4-4677-47ed-8b36-0859d7ea677c.png)

### frpc Version

0.48.0

### frps Version

0.48.0

### System Architecture

linux/amd64

### Configurations

[common]
bind_port = 8100
vhost_http_port = 8976
vhost_https_port = 8977
max_pool_count = 500
subdomain_host = proxy.mydomain.link 
authentication_method = token
token = mytoken
dashboard_port = 7500
dashboard_user = user
dashboard_pwd = password

[web]
type = http
type = https

### Logs

![error](https://user-images.githubusercontent.com/64725303/231017901-ca5c2d72-0c6e-423b-a27d-712b788430cb.png)

``` 
dex-b8250b3f.js:1 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at Ki (index-b8250b3f.js:1:13916)
    at kC (index-b8250b3f.js:1:15535)
    at kC (index-b8250b3f.js:1:15618)
    at kC (index-b8250b3f.js:1:15618)
    at kC (index-b8250b3f.js:1:15618)
    at kC (index-b8250b3f.js:1:15618)
    at kC (index-b8250b3f.js:1:15618)
    at kC (index-b8250b3f.js:1:15618)
    at kC (index-b8250b3f.js:1:15618)
    at kC (index-b8250b3f.js:1:15618)
Ki @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
Promise.then (async)
Rt @ index-b8250b3f.js:1
l @ index-b8250b3f.js:25
u @ index-b8250b3f.js:25
(anonymous) @ index-b8250b3f.js:25
(anonymous) @ index-b8250b3f.js:1
Ki @ index-b8250b3f.js:1
rn @ index-b8250b3f.js:1
Nd.t.__weh.t.__weh @ index-b8250b3f.js:1
RC @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
Promise.then (async)
OC @ index-b8250b3f.js:1
Bm @ index-b8250b3f.js:1
(anonymous) @ index-b8250b3f.js:1
j0 @ index-b8250b3f.js:1
Sp @ index-b8250b3f.js:1
pi @ index-b8250b3f.js:1
(anonymous) @ index-b8250b3f.js:1
e.<computed> @ index-b8250b3f.js:1
o @ index-b8250b3f.js:31
Nl @ index-b8250b3f.js:31
toggleRowExpansion @ index-b8250b3f.js:31
onClick @ index-b8250b3f.js:31
Ki @ index-b8250b3f.js:1
rn @ index-b8250b3f.js:1
r @ index-b8250b3f.js:1
index-b8250b3f.js:1 TypeError: Cannot read properties of null (reading 'emitsOptions')
    at tI (index-b8250b3f.js:1:17756)
    at k (index-b8250b3f.js:1:40124)
    at D (index-b8250b3f.js:1:39859)
    at p (index-b8250b3f.js:1:36530)
    at j (index-b8250b3f.js:1:42157)
    at B (index-b8250b3f.js:1:41673)
    at M (index-b8250b3f.js:1:39714)
    at p (index-b8250b3f.js:1:36456)
    at j (index-b8250b3f.js:1:42157)
    at B (index-b8250b3f.js:1:41673)
YD @ index-b8250b3f.js:1
Od @ index-b8250b3f.js:1
Ki @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
Promise.then (async)
OC @ index-b8250b3f.js:1
Bm @ index-b8250b3f.js:1
(anonymous) @ index-b8250b3f.js:1
j0 @ index-b8250b3f.js:1
Sp @ index-b8250b3f.js:1
pi @ index-b8250b3f.js:1
(anonymous) @ index-b8250b3f.js:1
e.<computed> @ index-b8250b3f.js:1
o @ index-b8250b3f.js:31
Nl @ index-b8250b3f.js:31
toggleRowExpansion @ index-b8250b3f.js:31
onClick @ index-b8250b3f.js:31
Ki @ index-b8250b3f.js:1
rn @ index-b8250b3f.js:1
r @ index-b8250b3f.js:1
index-b8250b3f.js:1 TypeError: Cannot read properties of null (reading 'emitsOptions')
    at tI (index-b8250b3f.js:1:17756)
    at k (index-b8250b3f.js:1:40124)
    at D (index-b8250b3f.js:1:39859)
    at p (index-b8250b3f.js:1:36530)
    at j (index-b8250b3f.js:1:42157)
    at B (index-b8250b3f.js:1:41673)
    at M (index-b8250b3f.js:1:39714)
    at p (index-b8250b3f.js:1:36456)
    at j (index-b8250b3f.js:1:42157)
    at B (index-b8250b3f.js:1:41673)
YD @ index-b8250b3f.js:1
Od @ index-b8250b3f.js:1
Ki @ index-b8250b3f.js:1
kC @ index-b8250b3f.js:1
Promise.then (async)
OC @ index-b8250b3f.js:1
Bm @ index-b8250b3f.js:1
(anonymous) @ index-b8250b3f.js:1
j0 @ index-b8250b3f.js:1
Sp @ index-b8250b3f.js:1
pi @ index-b8250b3f.js:1
(anonymous) @ index-b8250b3f.js:1
e.<computed> @ index-b8250b3f.js:1
o @ index-b8250b3f.js:31
Nl @ index-b8250b3f.js:31
toggleRowExpansion @ index-b8250b3f.js:31
onClick @ index-b8250b3f.js:31
Ki @ index-b8250b3f.js:1
rn @ index-b8250b3f.js:1
r @ index-b8250b3f.js:1
index-b8250b3f.js:1 TypeError: Cannot read properties of null (reading 'emitsOptions')
    at tI (index-b8250b3f.js:1:17756)
    at k (index-b8250b3f.js:1:40124)
    at D (index-b8250b3f.js:1:39859)
    at p (index-b8250b3f.js:1:36530)
    at j (index-b8250b3f.js:1:42157)
    at B (index-b8250b3f.js:1:41673)
    at M (index-b8250b3f.js:1:39714)
    at p (index-b8250b3f.js:1:36456)
    at j (index-b8250b3f.js:1:42157)
    at B (index-b8250b3f.js:1:41673)
Y
```

### Steps to reproduce

1. configure 3 o 4 proxy
2. access the consolle
3. Navigate through proxy information by exploding items

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by manprint** [comment]
Hi @fatedier, 
Thanks for the dashboard fix!
When will you release the fix? (maybe release 0.48.1)?
Thanks and good job!!!
