### ISSUE TITLE
frpc 0.53.0 crash

### ISSUE THREAD

**Issue by gdevenyi** [fatedier/frp#3920]
### Bug Description

```
2024/01/04 17:59:07 [I] [proxy_wrapper.go:239] [a81ac4e809a6f62e] [SSH2] health check success
panic: close of closed channel

goroutine 65 [running]:
github.com/fatedier/frp/client.(*Service).loopLoginUntilSuccess.func1()
        github.com/fatedier/frp/client/service.go:331 +0x517
github.com/fatedier/frp/pkg/util/wait.BackoffUntil(0xc000395e30, {0xd2f4a0, 0xc0002de2d0}, 0x1, 0xc000292720)
        github.com/fatedier/frp/pkg/util/wait/backoff.go:135 +0x118
github.com/fatedier/frp/client.(*Service).loopLoginUntilSuccess(0xc0001fc1c0, 0x4a817c800, 0x0)
        github.com/fatedier/frp/client/service.go:336 +0x1e9
github.com/fatedier/frp/client.(*Service).keepControllerWorking.func1()
        github.com/fatedier/frp/client/service.go:198 +0x32
github.com/fatedier/frp/pkg/util/wait.BackoffUntil(0xc000395fa8, {0xd2f4a0, 0xc00049c000}, 0x1, 0xc0000b2300)
        github.com/fatedier/frp/pkg/util/wait/backoff.go:135 +0x118
github.com/fatedier/frp/client.(*Service).keepControllerWorking(0xc0001fc1c0)
        github.com/fatedier/frp/client/service.go:195 +0x165
created by github.com/fatedier/frp/client.(*Service).Run
        github.com/fatedier/frp/client/service.go:173 +0x159
```

### frpc Version

0.53.0

### frps Version

0.53.0

### System Architecture

linux/amd64

### Configurations

frps.toml
```
bindPort = 7000
# Specify a UDP port for KCP.
#kcpBindPort = 7000
#quic_bind_port = 7000

webServer.port = REDACTED
# dashboard's username and password are both optional
webServer.user = "REDACTED"
webServer.password = "REDACTED"
auth.token = "REDACTED"

log.to = "./frps.log"
# trace, debug, info, warn, error
log.level = "info"
log.maxDays = 3
```

```
serverAddr = "REDACTED"
serverPort = 7000
#transport.protocol = "kcp"
#transport.protocol = "quic"
auth.token = "REDACTED"
loginFailExit = false

[[proxies]]
name = "SSH"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = REDACTED
transport.useEncryption = true
healthCheck.type = "tcp"

[[proxies]]
name = "SSH2"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = REDACTED
transport.useEncryption = true
healthCheck.type = "tcp"
```

### Logs

Nothing except for original bug of interest, regular operation.

### Steps to reproduce

No special steps taken.

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
尝试最新版

**Comment by superzjg** [comment]
https://github.com/fatedier/frp/releases/tag/v0.53.2
