### ISSUE TITLE
socks5加密压缩问题

### ISSUE THREAD

**Issue by Ramon403** [fatedier/frp#446]
版本是当前最新的0.13
服务端运行的win64版本，客户端是win32版本

然后都开启了kcp

客户端配置
[common]
server_addr = xx.xxxxx.com
server_port = 52000
privilege_token = 123456789
pool_count = 5
tcp_mux = true
user = xxx
protocol = kcp

[socket]
type = tcp
remote_port = 52040
use_encryption = true
use_compression = true

可以正常接连到服务端，但是一旦有数据传输，马上就报错frpc就退出了

控制台错误信息：
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x4 pc=0x62bf37]

goroutine 49 [running]:
github.com/fatedier/frp/vendor/github.com/armon/go-socks5.(*Server).ServeConn(0x11b900d0, 0x322840b8, 0x11ca4270, 0x0, 0x0)
        /home/wcl/go_projects/src/github.com/fatedier/frp/vendor/github.com/armon/go-socks5/socks5.go:158 +0x807
github.com/fatedier/frp/models/plugin.(*Socks5Plugin).Handle(0x11b900c0, 0x801260, 0x11c99d80)
        /home/wcl/go_projects/src/github.com/fatedier/frp/models/plugin/socks5.go:56 +0xad
github.com/fatedier/frp/client.HandleTcpWorkConnection(0x11afd5e4, 0x801220, 0x11b900c0, 0x11afd5c0, 0x804040, 0x11afb460)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/proxy.go:326 +0x159
github.com/fatedier/frp/client.(*TcpProxy).InWorkConn(0x11b28740, 0x804040, 0x11afb460)
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/proxy.go:111 +0x4b
created by github.com/fatedier/frp/client.(*Control).NewWorkConn
        /home/wcl/go_projects/src/github.com/fatedier/frp/client/control.go:188 +0x440

**Comment by Ramon403** [comment]
将客户端的加密和压缩配置删掉就可以正常使用了
use_encryption = true
use_compression = true

socks5的 可选参数在哪里能看到？ readme没看到有说
